# Generated by Django 3.2.20 on 2023-08-01 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('habit', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=250)),
                ('growth', models.IntegerField()),
            ],
        ),
    ]
