# Generated by Django 3.2.20 on 2023-08-03 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_watering'),
    ]

    operations = [
        migrations.AddField(
            model_name='watering',
            name='plant',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='main_app.plant'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='watering',
            name='water_required',
            field=models.CharField(choices=[('I', 'Infrequent'), ('R', 'Regular'), ('F', 'Frequent')], default='I', max_length=1),
        ),
    ]
